sonar.projectKey=rbrtjhn_printing-services
sonar.organization=rbrtjhn19
sonar.sources=printing_manager, printing_api
sonar.exclusions=**/*.g.dart,**/vendor/**,**/node_modules/**
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
